### ISSUE TITLE
Group Membership Sync

### ISSUE THREAD

**Issue by fleapower** [mrmattwilkins/google-contacts-sync#1]
I was reviewing the code and it appears you _are_ syncing groups.  One of the fields being sync'd is "memberships" and that is what holds the group memberships (https://developers.google.com/people/api/rest/v1/people#membership).  I must be missing something.  You are sure it doesn't sync groups?  I have not had a chance to test it.

**Comment by mrmattwilkins** [comment]
Hi there,
Yes, it is syncing the membership field.  It won't create a new label
though, or sync labels across (that is perhaps what you are using for
groups?).
Cheers
Matt

**Comment by fleapower** [comment]
OK.  I'm a bit lost.  If it is sync'ing the memberships field, how is it not sync'ing the categories the contacts belongs to?  Isn't that what the memberships field is?

I followed all of your instructions, but I'm afraid I may have not fully understood them:
1)  Do I need to get a credential json file for each user?  I didn't do that for Mike Adler's - I just used the credential file for one account.  If I do need to do a credential file for each user, do I need to create a new project for each user?
2)  Does it matter where I point the config file regarding credential json files and the credfiles?
3)  How does the script identify if a previous syncer has been used?  Does it look for the previous sync-state files?
4)  Finally, when I run sync.py, I'm still getting this:

Traceback (most recent call last):
  File "D:\Program Files\google-contacts-sync-main\sync.py", line 145, in <module>
    con = {
  File "D:\Program Files\google-contacts-sync-main\sync.py", line 146, in <dictcomp>
    cp[s]['user']: Contacts(cp[s]['keyfile'], cp[s]['credfile'])
  File "D:\Program Files\google-contacts-sync-main\contacts.py", line 109, in __init__
    self.get_info()
  File "D:\Program Files\google-contacts-sync-main\contacts.py", line 231, in get_info
    'name': p['names'][0]['displayName']
KeyError: 'names'

Thanks!

**Comment by mrmattwilkins** [comment]
Hi,

> OK.  I'm a bit lost.  If it is sync'ing the memberships field, how is
> it not sync'ing the categories the contacts belongs to?  Isn't that
> what the memberships field is?

I'm not sure what categories are sorry.  I think the memberships field
is for syncing group membership, but I don't create any groups, so I
doubt things will work if you have a bunch of people in a group, and you
sync that over to another account without that group.  But we are
getting ahead of ourselves, try getting the basic syncing working first.

> 1)  Do I need to get a credential json file for each user?

Yes

> I didn't do that for Mike Adler's - I just used the credential file
> for one account.  If I do need to do a credential file for each user,
> do I need to create a new project for each user?

I did.  Now I'm looking in the google cloud platform I see there is a
button to add other people to the project.  I might have been able to
have one project on one account and just add the others.  Anyway, that
isn't what I did.

> 2)  Does it matter where I point the config file regarding credential
> json files and the credfiles?

No, it doesn't matter.  If I was you I would point them to your current
keyfiles and credfiles.

> 3)  How does the script identify if a previous syncer has been used?
> Does it look for the previous sync-state files?

No, it doesn't.  It uses the csync-uid field though that Mike Adler's
code used if it is there, or creates it.

> 4)  Finally, when I run sync.py, I'm still getting this:
> 
> Traceback (most recent call last):
>   File "D:\Program Files\google-contacts-sync-main\sync.py", line 145, in <module>
>     con = {
>   File "D:\Program Files\google-contacts-sync-main\sync.py", line 146, in <dictcomp>
>     cp[s]['user']: Contacts(cp[s]['keyfile'], cp[s]['credfile'])
>   File "D:\Program Files\google-contacts-sync-main\contacts.py", line 109, in __init__
>     self.get_info()
>   File "D:\Program Files\google-contacts-sync-main\contacts.py", line 231, in get_info
>     'name': p['names'][0]['displayName']
> KeyError: 'names'

I think this is probably because you haven't got the above working.

Btw, I would run sync.py with the -v to get a bit more info.

Matt

**Comment by fleapower** [comment]
Thanks.  I went through everything and I'm still getting this when I run it:

D:\Program Files\google-contacts-sync-main>python sync.py -v
Loading configuration
Getting contacts
Traceback (most recent call last):
  File "D:\Program Files\google-contacts-sync-main\sync.py", line 145, in
<module>
    con = {
  File "D:\Program Files\google-contacts-sync-main\sync.py", line 146, in
<dictcomp>
    cp[s]['user']: Contacts(cp[s]['keyfile'], cp[s]['credfile'])
  File "D:\Program Files\google-contacts-sync-main\contacts.py", line 109,
in __init__
    self.get_info()
  File "D:\Program Files\google-contacts-sync-main\contacts.py", line 231,
in get_info
    'name': p['names'][0]['displayName']
KeyError: 'names'

Also, I  noticed that "last" in config.ini is not being updated.

**Comment by fleapower** [comment]
Tried everything from scratch.  No luck.  Same output as above.  Also, I'm only asked to authorize access for one account (the first one in the config.ini file).  If I remove the first account, the access is requested for the other account.

**Comment by mrmattwilkins** [comment]
So after you have authorized access for the first account, you quit your
browser, then what does the sync program do?  Just skip through the other
accounts?

**Comment by fleapower** [comment]
Yep.  Doesn't do anything.

**Comment by mrmattwilkins** [comment]
What do you mean doesn't do anything?  Just hangs there?  Are you sure you
have quit the browser and there isn't another one started up somewhere?

**Comment by fleapower** [comment]
Positive. Even after giving authorization for each account separately by
only having one account in the config file, it still gives the same message.

**Comment by mrmattwilkins** [comment]
So wait up.  After you have authenticated each account separately, you run
again and what happens?  Does it hang, or do you get that message you
posted before?

**Comment by fleapower** [comment]
That's correct, I get the same output as posted above after both accounts have been authenticated.

**Comment by fleapower** [comment]
Is it possible this will not work for legacy GSuite with a personal domain?

**Comment by mrmattwilkins** [comment]
Well done, glad you have found the problem!   No sorry, I don't even have a legacy GSuite domain to test it on.

**Comment by fleapower** [comment]
Thanks. Unfortunately, I have no idea how to fix it.

**Comment by mrmattwilkins** [comment]
Maybe start with some googling to see if people api is even supported on
those legacy gsuite domains?  If so, it might not be a huge deal, don't
know.

**Comment by fleapower** [comment]
I can get the People API to work inside Google Apps Script so I think it might be some type of username access issue.  It looks like the code is failing at line 146:

143     # get the contacts for each user
144     vprint('Getting contacts')
145    con = {
146      cp[s]['user']: Contacts(cp[s]['keyfile'], cp[s]['credfile'])
147      for s in cp.sections()
148   }

**Comment by mrmattwilkins** [comment]
No, it is failing on line 231 in contacts.py.  If I was you I would add this at line 220 in contacts.py:
print(p)
and just see what info we have in p

**Comment by fleapower** [comment]
Figured it out, but I don't know how to fix it.  Whenever the name is blank (for example, for a contact that is a company listing with no first or last name), contacts.py fails at line 231 as you corrected me.  I tried this on a Gsuite account and a regular Gmail account with the same results.  When I deleted the account w/o a name, it works.  I'll take a look at it tomorrow and see if an error handler allows the script to run (have to figure out how to do that in Python).

**Comment by fleapower** [comment]
What do you think of this?

        self.info = {}
        for p in self.get_all_contacts():
            try:
                p['names'][0]['displayName']
            except:
               # printing is just to identify when exception is called; will be removed
                print('')
                print('Name is blank.')
                print('')
                tempname = ''
            else:
                tempname = p['names'][0]['displayName']
            tagls = [
                kv['value']
                for kv in p.get('clientData', {})
                if kv.get('key', None) == SYNC_TAG
            ]
            self.info[p['resourceName']] = {
                'etag': p['etag'],
                'tag': tagls[0] if tagls else None,
                'updated': dateutil.parser.isoparse(
                    p['metadata']['sources'][0]['updateTime']
                ),
                'name': tempname
            }

**Comment by fleapower** [comment]
One more issue.  Even after taking care of the duplicates, I get this error:

raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 429 when requesting https://people.googleapis.com/v1/people/c2601577088583239757?personFields=addresses%2CageRanges%2Cbiographies%2Cbirthdays%2CcalendarUrls%2CclientData%2CcoverPhotos%2CemailAddresses%2Cevents%2CexternalIds%2Cgenders%2CimClients%2Cinterests%2Clocales%2Clocations%2Cmemberships%2Cmetadata%2CmiscKeywords%2Cnames%2Cnicknames%2Coccupations%2Corganizations%2CphoneNumbers%2Cphotos%2Crelations%2CsipAddresses%2Cskills%2Curls%2CuserDefined&alt=json returned "Quota exceeded for quota metric 'Critical read requests (Contact and Profile Reads)' and limit 'Critical read requests (Contact and Profile Reads) per minute per user' of service 'people.googleapis.com' for consumer 'project_number:737087378495'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'quota_limit': 'CriticalReadsPerMinutePerProjectPerUser', 'service': 'people.googleapis.com', 'quota_metric': 'people.googleapis.com/critical_read_requests', 'consumer': 'projects/737087378495'}}]">

**Comment by mrmattwilkins** [comment]
Not quite, I think you need to use the company name if the real name isn't
there.
Do a pull, I have put that in.

Also, that other error is simply a rate limiting error.  You will get that
if you do too many requests to google.  All this mucking about probably has
caused that.

**Comment by fleapower** [comment]
Did the pull and it seems to be working now as far as the duplicates go (had to do some cleanup, but seems to be working).

I'm still getting the rate limiting error.  Stopped at 32 this time - I have 5,000+ contacts.  I might need to figure out how to throttle the script on the initialization.

**Comment by mrmattwilkins** [comment]
Yeah the initialization is really intensive.  I could potentially make it
far quicker, but it would be more complicated.  I'll think about it next
week.

In the meantime if you just want to get it to work, and are willing to let
it just run in the background, put a sleep(10) or something like that at
line 173.  If necessary you can increase the sleep, or if that doesn't work
stick another pause at line 181.  You will need an 'import time' at the top
of the script too.

This will mean it takes 10 seconds per contact (per account if there is a
pause at 181).  So if you have 5000 contacts over a couple accounts you are
looking at 10*5000 = 14hours!  (or 28 hours if you pause at line 181).
That is pretty annoyingly slow.

Like I said I might get round to speeding this up, but give it a try
anyway.  I'm actually a bit surprised you need to do this at all if you
were using Michael Adler's code since the sync tags should be in there
already.

Matt

**Comment by fleapower** [comment]
The sleep seems to be working, but now I'm getting a new error:

http.py", line 935, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://people.googleapis.com/v1/people/c5808066010217886934:updateContact?updatePersonFields=addresses%2Cbiographies%2Cbirthdays%2CclientData%2CemailAddresses%2Cevents%2CexternalIds%2Cgenders%2CimClients%2Cinterests%2Clocales%2Clocations%2Cmemberships%2CmiscKeywords%2Cnames%2Cnicknames%2Coccupations%2Corganizations%2CphoneNumbers%2Crelations%2CsipAddresses%2Curls%2CuserDefined&alt=json returned "Cannot have more than one person.names per source.". Details: "Cannot have more than one person.names per source.">

When I lookup that contact (people/c5808066010217886934), it doesn't seem to exist.

**Comment by watsapptv** [comment]
I'm going off-topic for a moment. This new people API is have me a way.. need some help with my little code 

my setup is that i have a google form that link to google sheet and every new contact that get added my code below would run in google app script and add or update my google contact. it was work over a few years now but a couple days ago it stop work. can you rewrite this with the new people api.  thanks inadvance 

App script code below

function fromSubmitted(e){
  const info = e.namedValues;
  const contactArray = ContactsApp.getContactsByPhone(info["WhatsApp Number"]);
  if(contactArray.length === 0){
    addContact(info);
  } else {
    updateContact(contactArray[0],info);
  }  
}

function addContact(info) {
  const c = People.People.createContact(info["User Name"], info["Last Name"], info[""]);
  c.addPhone(ContactsApp.Field.MOBILE_PHONE, info["WhatsApp Number"]);
  c.setMiddleName(info["Birth Year"]);
  c.setSuffix(info["Parish"]);
  c.setPrefix(info["Gender"]);
  c.addCompany(info[""],info[""]);
  c.setNotes(info["Phone Network"]);
  const cg = ContactsApp.getContactGroups();
  c.addToGroup(cg[4]);
  
}

function updateContact(c,info) {
  c.setGivenName(info["First Name"]);
  c.setMiddleName(info["Birth Year"]);
  c.setSuffix(info["Parish"]);
  c.setPrefix(info["Gender"]);
  c.setNotes(info["Phone Network"]);
  c.addCompany(info[""],info[""]);
  c.setFamilyName(info["Last Name"]);
   
}

**Comment by mrmattwilkins** [comment]
Hi watsapptv ,
Please open another issue, not put your request in this one.
thanks
Matt

**Comment by mrmattwilkins** [comment]
> The sleep seems to be working, but now I'm getting a new error:
> 
> http.py", line 935, in execute
> raise HttpError(resp, content, uri=self.uri)
> googleapiclient.errors.HttpError: <HttpError 400 when requesting https://people.googleapis.com/v1/people/c5808066010217886934:updateContact?updatePersonFields=addresses%2Cbiographies%2Cbirthdays%2CclientData%2CemailAddresses%2Cevents%2CexternalIds%2Cgenders%2CimClients%2Cinterests%2Clocales%2Clocations%2Cmemberships%2CmiscKeywords%2Cnames%2Cnicknames%2Coccupations%2Corganizations%2CphoneNumbers%2Crelations%2CsipAddresses%2Curls%2CuserDefined&alt=json returned "Cannot have more than one person.names per source.". Details: "Cannot have more than one person.names per source.">
> 
> When I lookup that contact (people/c5808066010217886934), it doesn't seem to exist.

Hi Fleapower,
You will want to do a git pull (and read issue #2 ) since I think I've sorted this
Cheers
Matt
