### ISSUE TITLE
contact modified even without any modification

### ISSUE THREAD

**Issue by Rarder44** [mrmattwilkins/google-contacts-sync#10]
I encountered the following problem:
sometimes, even without changing any information in any contact, I find myself with some contacts that are reported as to be synchronized.

is it a known "problem" (google likes to update the "updateTime" field at random?), or is it something that only happens to me?

**Comment by Rarder44** [comment]
maybe I found an answer:
when you send an email to a contact, the item "Recent interactions" appears in the contact's interface.
the contacts to whom I have just sent an email are asked to synchronize.

**Comment by mrmattwilkins** [comment]
Cool, well done.

**Comment by Rarder44** [comment]
it doesn't actually solve all cases: sometimes there are groups of contacts that update at 2: 00/3: 00 in the morning.

**Comment by mrmattwilkins** [comment]
If it bothers you, perhaps you could add some code to do a full dump of the
contacts before syncing.  Save that somewhere on every run and inspect and
see what has changed?  I'm personally not bothered, but it would be
interesting to know for sure.  I (probably like you) have a lot of devices
(various computers and phones) that sync contacts with google, could easily
be one of those just touching something.

**Comment by Rarder44** [comment]
as soon as I have some time, I try to write something and let you know

**Comment by mrmattwilkins** [comment]
Did you get anywhere with figuring this?

**Comment by Rarder44** [comment]
no, I had other commitments and this "bug" in the end does nothing but waste a little more time during sync... nothing "serious".
Even though for some time now I've been seeing far fewer contacts synchronizing, has it sorted itself out? (maybe google fixed something...)

**Comment by mrmattwilkins** [comment]
OK, glad it has come right.
