### ISSUE TITLE
google-contacts-sync problem

### ISSUE THREAD

**Issue by watsapptv** [mrmattwilkins/google-contacts-sync#3]
This new people API has me away.. need some help with my little code

my setup is that I have a google form that link to a google sheet and every new contact that gets added to my code below would run in google app script and add or update my google contact. it was working over a few years now but a couple of days ago it stops work. can you rewrite this with the new people api. thanks inadvance

App script code below

function fromSubmitted(e){
const info = e.namedValues;
const contactArray = ContactsApp.getContactsByPhone(info["WhatsApp Number"]);
if(contactArray.length === 0){
addContact(info);
} else {
updateContact(contactArray[0],info);
}
}

function addContact(info) {
const c = People.People.createContact(info["User Name"], info["Last Name"], info[""]);
c.addPhone(ContactsApp.Field.MOBILE_PHONE, info["WhatsApp Number"]);
c.setMiddleName(info["Birth Year"]);
c.setSuffix(info["Parish"]);
c.setPrefix(info["Gender"]);
c.addCompany(info[""],info[""]);
c.setNotes(info["Phone Network"]);
const cg = ContactsApp.getContactGroups();
c.addToGroup(cg[4]);

}

function updateContact(c,info) {
c.setGivenName(info["First Name"]);
c.setMiddleName(info["Birth Year"]);
c.setSuffix(info["Parish"]);
c.setPrefix(info["Gender"]);
c.setNotes(info["Phone Network"]);
c.addCompany(info[""],info[""]);
c.setFamilyName(info["Last Name"]);

}

**Comment by mrmattwilkins** [comment]
Hi,

No I will not write your code for you sorry, but I can tell you where to look so you can figure it out.

Have a look contacts.py at line 335.  That is for adding a contact.  Essentially you need to take your info dict and turn it into an acceptable body, line 165 in contacts.py shows you the format for body.

Updating isn't much more difficult at all.  Have a look at line 343.  The service.people().updateContact.  It takes the same formatted body, and you just need to specify the resourceName.

Alternatively you can have a look at
https://github.com/mashu3/google-contacts-sync
that guy is syncing from a spreadsheet, basically what you are doing!  I think you can probably just use this code.

Good luck

**Comment by watsapptv** [comment]
ok. I'm not fully a tech guy but I can help myself a little. I will look at your code to try to figure it out.. with the other code from that guy. I'm totally confused I don't even know how to deplore that code

**Comment by watsapptv** [comment]
After 3 hours.. Look like i don't know what I'm doing. 

function addContact(info) {
new_contact = self.service.people().createContact(
body = {
            'names':[{'givenName':Tom, 'familyName':Jerry,}],
            'emailAddresses':[{'value':test@gmail.com, 'type':'work'}],
            'phoneNumbers':[{'value':phone_mobile, 'type':'mobile'}]
        }).execute()}

im lost.
