### ISSUE TITLE
Sync contactGroups and membership

### ISSUE THREAD

**Issue by erseco** [mrmattwilkins/google-contacts-sync#5]
I'm using tags to organize contacts and I want to sync them. Before copying the membership value you should sync the contactGroups and later sync the membership, because the IDs will be different, I was trying to do by myself but seems a little complicated, if you have any idea on how to do this sync I can try to code it and PR your code.

This issue is related to #1 

Best!

**Comment by fleapower** [comment]
I needed the same thing (group sync) so I wrote a Google script to do it.  Still a work in progress, but it is functional.

https://github.com/fleapower/Google-Script-Contacts-Sync

**Comment by mrmattwilkins** [comment]
thanks fleapower.  closing this since it is in the other issue too.  cheers.
