### ISSUE TITLE
Google Script Contacts Sync (including Groups)

### ISSUE THREAD

**Issue by fleapower** [mrmattwilkins/google-contacts-sync#6]
Matt, I posted this over on Mike Adler's page, but I'm not sure if you'll read it.  I really needed group sync, so I wrote a Google script from scratch to do contacts sync which includes group sync. It resembles more of Frankenstein's monster than pretty code. It is a work in progress, but it is functional. I've been using it for a couple of weeks with four accounts. You (or anyone) are welcome to try it if you'd like.

https://github.com/fleapower/Google-Script-Contacts-Sync

**Comment by mrmattwilkins** [comment]
Thanks Fleapower, wouldn't it be nice if google provided such a feature (as
well as syncing the people contacts too) so we didn't have to do all this!

**Comment by fleapower** [comment]
Agree.  It seems completely nonsensical to me they don't provide this.  Could you imagine the data harvesting and subsequent ad targeting they could do by knowing which users are sharing contacts?

**Comment by mrmattwilkins** [comment]
Merge request #8 provides group syncing, so all done now.
